baseURL = "http://caeos.github.io/"
languageCode = "en-us"
title = "Coner"
theme = "docdock"
publishDir = "docs"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  themeVariant = "coner"
  noSearch = true
  noHomeIcon = true

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> Github organization"
url = "https://github.com/caeos"
